### ISSUE TITLE
USER STORY: manage available post fields

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#1]
As a **superuser** I can **manage available post fields** so that I can **standardise and structure posts**.

**Acceptance Criteria**
- [x] Fields will appear on post form.

**Tasks**
- [x] Create model.
- [x] Register model in admin.py
- [x] Add metadata and dunder so posts are recognisable and ordered within django admin.

**Comment by alanjameschapman** [comment]
Add to edblog/models.py:

```python
class Post(models.Model):
    """
    Stores a single blog post entry related to :model:`auth.User`.
    """

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.CharField(max_length=200, blank=True)
``` 
Add to edblog/admin.py:
```python
admin.site.register(Post)
```

**Comment by alanjameschapman** [comment]
Add to Post class in edblog/models.py:
```python
class Meta:
        ordering = ['-created_on', 'author']

    def __str__(self):
        return self.title
``` 

| Before | After |
| --- | --- |
| ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/62f547df-db42-4769-86ab-e461d1cb1924) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/1dbad970-d783-4828-9ba7-bdbd399e87cc) |
