### ISSUE TITLE
USER STORY: create Entity Relationship Diagrams

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#11]
As a **developer** I can **create ERDs** so that I can **define and visualise how database tables relate to each other**.

**Acceptance Criteria**
- [x] Tables show relationship types e.g. 1-2-1
- [x] Tables show field types (fed into Models).

**Tasks**
- [x] Create diagrams in Lucidchart.

**Comment by alanjameschapman** [comment]
See ERD in README.
