### ISSUE TITLE
USER STORY: create user journey

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#13]
As a **developer** I can **create user journey** so that I can **define and visualise how database tables relate to each other**.

**Acceptance Criteria**
- [x] Diagram shows site navigation.
- [x] Blocks used: display, flow control, function and user input.

**Tasks**
- [x] Create diagrams in Lucidchart.

**Comment by alanjameschapman** [comment]
Wireframes #10 (closed) effectively shows user journey and has helped me understand how database models will relate to each other.

To be left open subject to review at mentor meeting 1.

**Comment by alanjameschapman** [comment]
As discussed at mentor meeting, it would still be valuable to create a detailed user flow diagram but this can be deprioritized, as there is enough info on the wireframes to help build the project. Story points reduced from 2 to 1.

**Comment by alanjameschapman** [comment]
![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/9d56f2de-c742-4aa3-9f6f-d3662e9464b4)
