### ISSUE TITLE
USER STORY: tag content

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#14]
As a **teacher** I can **tag content** so that I can **enable students to search for a specific topic or skill**.

**Acceptance Criteria**
- [ ] Posts can be tagged during creation or updating
- [ ] Tags appear alongside posts.

**Tasks**
- [ ] Create model, view and template.

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
