### ISSUE TITLE
USER STORY: use Rich Text Formatting

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#15]
As a **teacher** I can **use Rich Text Formatting** so that I can **create engaging content**.

**Acceptance Criteria**
- [x] Teacher can add images, media, tables etc.

**Tasks**
- [x] Install django summernote
- [x] Update whiteboard/urls.py
- [x] Update edblog/admin.py

**Comment by alanjameschapman** [comment]
Update whiteboard/urls.py:

```python
urlpatterns = [
    ...
    path("summernote/", include("django_summernote.urls")),
    ...
]
``` 
 
Add PostAdmin class with decorator (and removing existing registration) to edblog/admin.py:

```python
...
from django_summernote.admin import SummernoteModelAdmin


@admin.register(Post)
class PostAdmin(SummernoteModelAdmin):

    list_display = ('title', 'slug', 'status')
    search_fields = ['title']
    list_filter = ('status',)
    prepopulated_fields = {'slug': ('title',)}
    summernote_fields = ('content',)

# Register your models here.
~~admin.site.register(Post)~~
admin.site.register(Comment)
``` 

| Before | After |
| --- | --- |
| ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/ca93a985-7be5-42ac-b871-86f20ad5a0a4) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/1d980f71-2930-44ed-9c06-7b3234efb5eb) |
