### ISSUE TITLE
USER STORY: post content

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#16]
As a **teacher** I can **post content** so that I can **provide information to students on a topic of my choice**.

**Acceptance Criteria**
- [x] Teacher can CREATE posts via a crispy form
- [x] Teacher is notified of posting
- [x] Teacher can use RTF
- [x] Teacher can cancel posting
- [x] Teacher can approve instantly.
- [x] Validation to ensure title is unique.

**Tasks**
- [x] Create model
- [x] Add to admin.py
- [x] Create view
- [x] Create template.

**Comment by alanjameschapman** [comment]
| Basic crispy form displayed within new create_post template | Slug, status and RTF can only be edited within admin panel |
| --- | --- |
|![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/95b83efa-71b4-4050-a69b-6b0005cd2065) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/4eddb65b-a6b1-458a-860e-473ffab0d4a8) |

**Comment by alanjameschapman** [comment]
**Validation to ensure title is unique**

Amend view:

```python
if form.is_valid():
            post = form.save(commit=False)  # Don't save the form to the database yet
            post.author = request.user  # Set the author field to the current user
            post.slug = slugify(post.title)
            try:
                post.save()  # Try to save the form to the database
            except IntegrityError as e: # If the slug is not unique, add an error to the form
                if 'slug' in str(e):
                    form.add_error('title', 'A post with this title already exists - please choose a different title. Case, punctuation and spacing are ignored.')
                    return render(request, 'edblog/create_post.html', {'form': form})
                raise e
            return redirect('home')
``` 

Amend model:
```python
title = models.CharField(
        max_length=200,
        unique=True,
        error_messages={
            'unique': 'A post with this title already exists - please choose a different title. Case, punctuation and spacing are ignored.',
        },)
``` 
User given specific feedback:

![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/0658c102-e174-4b6b-835b-7543ece05889)

**Comment by alanjameschapman** [comment]
Summernote widget added to forms.py

```python
from django_summernote.widgets import SummernoteWidget
...
class PostForm(forms.ModelForm):
    ...
    content = forms.CharField(widget=SummernoteWidget())
``` 

![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/e04654d1-301a-48d2-bc2f-031b14a48fb4)

**Comment by alanjameschapman** [comment]
Add styled cancel button (anchor tag linked to home) and style submit button:

```python
<button type="submit" class="btn btn-success" aria-label="Submit">Submit</button>
<a href="{% url 'home' %}" class="btn btn-danger" aria-label="Cancel">Cancel</a>
``` 

Screenshot:

<img width="587" alt="16-3" src="https://github.com/alanjameschapman/whiteboard/assets/137620143/5aa13b78-d45c-47ad-bea8-39c14fc0fc9d">

**Comment by alanjameschapman** [comment]
Modify the create_post view to set the status of the post to 0 for "Draft" and 1 for "Published" when the respective button is clicked:

```python
def create_post(request):
    ...
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)  # Don't save the form to the database yet
            post.author = request.user  # Set the author field to the current user
            post.slug = slugify(post.title)
            if 'submit' in request.POST:
                post.status = 1 # publish the post
            elif 'save_draft' in request.POST:
                post.status = 0 # save the post as a draft
            try:
                post.save()  # Try to save the form to the database

``` 

https://github.com/alanjameschapman/whiteboard/assets/137620143/025819b9-b4fb-494c-b5d9-702e6dcc5053
