### ISSUE TITLE
USER STORY: delete content

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#18]
As a **teacher** I can **delete content** so that I can **remove outdated or incorrect information**.

**Acceptance Criteria**
- [x] Teacher can DELETE posts
- [x] Teacher is notified of deletion.

**Tasks**
- [x] Create model, view and template.

**Comment by alanjameschapman** [comment]
Acceptance criteria can be met via admin panel, but once the remaining models are in place, this can be moved to the front end for later development.
