### ISSUE TITLE
USER STORY: post draft content

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#19]
As a **teacher** I can **post draft content** so that I can **complete the post at a later date**.

**Acceptance Criteria**
- [x] Teacher can select 'draft' button
- [x] Teacher is notified of draft posting.

**Tasks**
- [x] Create model, view and template.

**Comment by alanjameschapman** [comment]
See Issue #16 for code and video showing this functionality.

**Comment by alanjameschapman** [comment]
| Teacher can select draft for new or existing post | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/0eb9dcd1-1626-4a54-b474-4d5ca88f6a1b) |
| - | - |
| Draft appears in teacher's post list but not in student's | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/55b80e22-8c09-4bb6-9edf-6c645bb08f57) |
