### ISSUE TITLE
USER STORY: set quizzes

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#2]
As a **teacher** I can **set quizzes** so that I can **assess my students' understanding**.

**Acceptance Criteria**
- [ ] Teacher can set a questions and multiple answers
- [ ] Teacher can select which answer is correct"

**Tasks**
- [ ] Research how to integrate Vue.js into django framework.
- [ ] Integrate Vue.js
- [ ] Write some teacher quizzes to demonstrate functionality."

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
