### ISSUE TITLE
USER STORY: update my user profile

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#20]
As a **user** I can **update my user profile** so that I can **personalise my UX**.

**Acceptance Criteria**
- [ ] User can choose profile avatar, subjects and teachers.
- [ ] User is notified of registration."

**Tasks**
- [ ] Create model, view and template.

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
