### ISSUE TITLE
USER STORY: view all posts summarized

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#23]
As a **user** I can **view all posts summarized** so that I can **browse topics**.

**Acceptance Criteria**
- [x] Users can READ posts.
- [x] Posts are summarised (photo, title, snippet).
- [x] Posts are paginated.
- [x] Clicking on a post will enable user to view post detail
- [x] Posts are relevant to user

**Tasks**
- [x] Add model
- [x] Add view
- [x] Add template
- [x] Add posts.json to edblog/fixtures
- [x] Install Cloudinary and connect API.

**Comment by alanjameschapman** [comment]
Add PostList class to edblog/views:

```python
class PostList(generic.ListView):
    queryset = Post.objects.all()
    template_name = "post_list.html"
``` 

Add basic template to edblog/templates/edblog/post_list.html (this will be developed further):

```python
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views Part 1</title>
</head>

<body>
    <h1>Posts list</h1>
    {% for post in object_list %}
    <h2>{{post.title}}</h2>
    <p>{{post.excerpt}}</p>
    <p>Author: {{post.author}}</p>
    {% endfor %}
</body>

</html>
``` 

Add posts.json to edblog/fixtures to quickly check how a large dataset will be displayed.

| Admin | Deployed |
|---|---|
| ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/a350301c-a13d-43b9-b679-416d94d3d52d) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/3d7bb841-e3d5-47ac-b42a-6cfbfbd56d9c) |

**Comment by alanjameschapman** [comment]
Add base and index.html templates with snippets, paginate, add boilerplate css.

| Local | Deployed
| --- | --- |
| ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/7d703a2b-33f5-45d9-8f2c-570af43499ce) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/c3d679fb-06d9-45cc-9e51-110f9769c15c) |

**Comment by alanjameschapman** [comment]
Install Cloudinary and connect API.

Update Post model and index.html with DTL.

**Result**

![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/847d9538-9e40-46e8-b3c7-52095500556e)

**Comment by alanjameschapman** [comment]
Students can now see relevant posts, depending on their enrolment. Teachers can see only posts which they authored.

| Enrolment | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/42ec2be1-b653-481c-ae04-3bdaba408a8b) |
| --- | --- |
| Posts | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/5e355159-fd3e-4a2b-9fca-c0b13af98f81) |
| Teacher 1 | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/7287b50c-51f9-4b6a-9f20-9b692fe002b8) |
| Teacher 2 | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/a9ca2723-92c4-44a2-a9e4-7a4d743dbfb0) |
| Student 1 | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/de398fe1-db79-4dfc-97f4-5a9e44ee4724) |
| Student 2 | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/db75e48a-e6e4-4427-a94d-66ec18ed765a) |
