### ISSUE TITLE
USER STORY: search for content

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#24]
As a **user** I can **search for content** so that I can **quickly find help on any given topic**.

**Acceptance Criteria**
- [ ] Posts can be sorted by 'popular' i.e. most comments. Default is newest first.
- [ ] Users can see which posts they have commented on.
- [ ] Users can enter tags or search by strings.

**Tasks**
- [ ] Create model, view and template.

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
