### ISSUE TITLE
USER STORY: reply to comments

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#26]
As a **user** I can **reply to comments** so that I can **engage in discussions**.

**Acceptance Criteria**
- [x] User can reply to comments
- [ ] ~~Replies are indented from original comment~~
- [ ] ~~Replies follow same approval process as standard comments~~

**Tasks**
- [x] Create model, view and template.

**Comment by alanjameschapman** [comment]
The implementation of user story #9 for commenting on posts was deemed sufficient for replying to comments.
