### ISSUE TITLE
USER STORY: edit or delete my comments

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#28]
As a **user** I can **edit or delete my comments** so that I can **amend my comments**.

**Acceptance Criteria**
- [x] User can UPDATE or DELETE comments
- [x] Editing an approved comments needs approval
- [x] Modal to confirm deletion.

**Tasks**
- [x] Add view
- [x] Add to template
- [x] Add js.

**Comment by alanjameschapman** [comment]
| Edit a comment | Delete a comment modal confirmation |
| --- | --- |
| <img width="1328" alt="28-1" src="https://github.com/alanjameschapman/whiteboard/assets/137620143/b7205d83-8b95-4f34-9fda-2c3f23e306c7"> | <img width="1157" alt="28-2" src="https://github.com/alanjameschapman/whiteboard/assets/137620143/449b2487-4098-4db4-a04b-68626c39b3be"> |
