### ISSUE TITLE
USER STORY: answer quizzes

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#3]
As a **student** I can **answer quizzes** so that I can **get feedback on my understanding on a given topic**.

**Acceptance Criteria**
- [ ] Student can select which answer they think is correct.
- [ ] Student receives immediate feedback per question.
- [ ] Student receives overall score.

**Tasks**
- [ ] Create model, view and template.

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
