### ISSUE TITLE
USER STORY: moderate comments frontend

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#35]
As a **teacher** I can **moderate comments frontend** so that I can **speed up the comment approval process**.

**Acceptance Criteria**
- [x] Student comments relating to a specific post visible to teacher
- [x] Approve and deny buttons visible to teacher only
- [x] Clicking approve button makes comment visible to all relevant users
- [x] Clicking deny button deletes comment and notifies student

**Tasks**
- [x] Add DTL to front end (teacher profile, post detail or both)
- [x] Add event listeners to js
- [x] Add view functions for both
- [x] Update urls and models if necessary.

**Comment by alanjameschapman** [comment]
| Student comments need teacher approval | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/60874c88-3ed4-4ef8-aa97-4992a595a289) |
| - | - |
| Comment approve button available to teacher frontend | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/76a6eefe-bf26-45bf-b105-8bb7cfa5d8bb) |
| Clicking Approve makes comments visible to student | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/9d306fb6-f134-4663-93ab-ec0dd87ad932) |
| Teacher comments are auto-approved, even after Edit | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/0221bbb6-3fec-4afe-bda2-161a46d666c0) |
