### ISSUE TITLE
USER STORY: register and log in/out with username and password

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#4]
As a **user** I can **register and log in/out with username and password** so that I can **access the site**.

**Acceptance Criteria**
- [x] User is notified of registration
- [x] User can input login details to enter site
- [x] User is notified of login/logout
- [x] User can select 'remember me'.

**Tasks**
- [x] Install and connect Allauth
- [x] Create model, view and template.

**Comment by alanjameschapman** [comment]
| Sign in | Sign out |
| --- | --- |
| ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/7b46be4e-4068-4079-8d91-b4e1f50ddda1) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/e9b8ce00-cc66-4806-b92f-d67c85ca525f) |

**Comment by alanjameschapman** [comment]
| Registered | Signed out |
| --- | --- |
| ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/0a3c7a5c-300f-42e8-83a6-f7b5200906c2) | ![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/89254b32-5dfe-427f-b54d-6b0ade522681) |
