### ISSUE TITLE
USER STORY: enrol student frontend

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#41]
As a **teacher** I can **enrol student frontend** so that I can **provide content to relevant users**.

**Acceptance Criteria**
- [ ] Teacher can create sets for a given subject
- [ ] Teacher can add students to sets

**Tasks**
- [ ] Create views and templates

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
