### ISSUE TITLE
Step 1 - create welcome screen

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#45]
As a **gamer** I can **see a welcome screen** so that I can **select my desired option**.

**Acceptance Criteria**
- [ ] Buttons visible
- [ ] High scores visible

**Tasks**
- [ ] Add play button
- [ ] Add help button
- [ ] Add high scores field
