### ISSUE TITLE
Step 4 - gamer controls tetrominoes

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#48]
As a **gamer** I can **control the tets** so that I can **play the game**.

**Acceptance Criteria**
- [ ] Tets move left and right.
- [ ] Tets rotate.
- [ ] Tets accelerate down

**Tasks**
- [ ] Code left and right.
- [ ] Code rotation.
- [ ] Code acceleration.
