### ISSUE TITLE
Step 5 - remove completed rows and update scoreboard

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#49]
As a **gamer** I can **clear completed rows** so that I can **improve my score**.

**Acceptance Criteria**
- [ ] Completed rows are removed...
- [ ] ...then score updates (1pt per row)
- [ ] Game ends if no space at top...
- [ ] ...then gamer can play again or go home.

**Tasks**
- [ ] Code row removal
- [ ] Code scoring logic
- [ ] Code score updating
- [ ] Code game end and go home.
