### ISSUE TITLE
USER STORY: accept or deny requests from students

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#5]
As a **teacher** I can **accept or deny requests from students** so that I can **control which students can access/comment on my posts**.

**Acceptance Criteria**
- [x] Teacher is notified when a student selects them as their teacher.
- [x] Via the admin panel, Teacher can enrol student in their subjects/sets once student user profiles have been created.

**Tasks**
- [x] Add enrolment model with relationships to students and sets.

**Comment by alanjameschapman** [comment]
For this project, students will be enrolled by the teacher, once the students have created a user account:

![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/37ad5fbe-2793-4619-946a-5d30a025ea80)
