### ISSUE TITLE
USER STORY: log in with email/socials

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#6]
As a **user** I can **log in with email/socials** so that I can **access the site**.

**Acceptance Criteria**
- [ ] User can select Google, Twitter or Facebook.
- [ ] User is notified of login.

**Tasks**
- [ ] Create model, view and template.

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
