### ISSUE TITLE
USER STORY: reset my password

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#7]
As a **user** I can **reset my password** so that I can **access the site if I have forgotten my password.**.

**Acceptance Criteria**
- [ ] User can click 'forgot password' button.
- [ ] User then enters email.
- [ ] User then receives email to reset password.
- [ ] User then inputs new password (twice).
- [ ] User authentication details updated.

**Tasks**
- [x] Read django-allauth docs.
- [ ] Configure project to enable functionality.
- [ ] Create model, view and template.
- [ ] Style the forgot password page to align with other authentication pages

**Comment by alanjameschapman** [comment]
As discussed at mentor review meeting, acceptable to remove the functionality and refer user to admin etc. Moved to backlog for future development.

![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/e1dc2e8c-a035-47ac-ae69-cd817f247b5e)

**Comment by alanjameschapman** [comment]
Closed and kept in backlog for future development.
