### ISSUE TITLE
USER STORY: moderate student comments

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#8]
As a **teacher** I can **moderate student comments** so that I can **ensure appropriate content**.

**Acceptance Criteria**
- [x] Teacher can approve comments back end
- [x] User can DELETE comments

**Tasks**
- [x] Create model, view and template

**Comment by alanjameschapman** [comment]
Editing/deleting comments can be done front end by author only.

This functionality and approval can be done via the admin panel currently, but once the remaining models are in place, this can be moved to the front end.

Promoting/liking comments has been moved to its own user story for later development.
