### ISSUE TITLE
USER STORY: comment on posts

### ISSUE THREAD

**Issue by alanjameschapman** [alanjameschapman/whiteboard#9]
As a **user** I can **comment on posts** so that I can **ask questions to the teacher/student**.

**Acceptance Criteria**
- [x] Users can CREATE comments on specific posts.
- [x] Student comments appear 'for approval' by teacher.
- [x] User is notified that comment awaits approval.

**Tasks**
- [x] Create model
- [x] Register model in admin.py
- [x] Add metadata and dunder so comments are recognisable and ordered within django admin.
- [x] Install crispy forms and crispy bootstrap

**Comment by alanjameschapman** [comment]
Add to edblog/models.py:
```python
class Comment(models.Model):
    """
    Stores a single comment entry related to :model:`edblog.Post`.
    """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
``` 

Add to edblog/admin.py:
```python
admin.site.register(Comment)

```

**Comment by alanjameschapman** [comment]
Add to Comment class in edblog/models.py:
```python
class Meta:
        ordering = ['post', '-created_on', 'author']

    def __str__(self):
        return self.content
``` 
Although there is only one comment presently, the ordering above will group comments by post, then date created, then author.

|Before|After|
|---|---|
|![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/701dc4c4-0340-45cb-a4cf-8256ef7e96ba)|![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/395f2397-2148-46e4-b157-fa319029fa16)|

**Comment by alanjameschapman** [comment]
Install crispy forms and crispy bootstrap, update post_detail view, and update template to include styled form.

![Image](https://github.com/alanjameschapman/whiteboard/assets/137620143/ad7e708b-024a-404b-b7de-3cdca8173958)
